### ISSUE TITLE
IE 11 support

### ISSUE THREAD

**Issue by Djepri** [geosigno/simpleParallax#19]
I love this plugin, 
but look like doesn't support IE11.

I think is because the "closest" function only work in a modern browser

Thanks

**Comment by geosigno** [comment]
Thanks for your interest :)

Yes, the closest polyfill was initially set before version 5 but it has been removed, so no support for IE11 is provided.

The reason is the render was very bad on IE11. No matter how hard the process has been optimized, this is was still very ugly. IE11 was just not "strong" enough to render smooth parallax transitions.

Still, if you really want to support IE11, you can include this polyfill in your script before executing simpleParallax: https://developer.mozilla.org/fr/docs/Web/API/Element/closest#Polyfill

**Comment by DanielRuf** [comment]
@wokenqingtian so this has to be patched in the library, am I correct?
